// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calpb/calc.proto

package calpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AVGRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AVGRequest) Reset()         { *m = AVGRequest{} }
func (m *AVGRequest) String() string { return proto.CompactTextString(m) }
func (*AVGRequest) ProtoMessage()    {}
func (*AVGRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edfed136edde2186, []int{0}
}

func (m *AVGRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AVGRequest.Unmarshal(m, b)
}
func (m *AVGRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AVGRequest.Marshal(b, m, deterministic)
}
func (m *AVGRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AVGRequest.Merge(m, src)
}
func (m *AVGRequest) XXX_Size() int {
	return xxx_messageInfo_AVGRequest.Size(m)
}
func (m *AVGRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AVGRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AVGRequest proto.InternalMessageInfo

func (m *AVGRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AVGResponse struct {
	Average              float32  `protobuf:"fixed32,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AVGResponse) Reset()         { *m = AVGResponse{} }
func (m *AVGResponse) String() string { return proto.CompactTextString(m) }
func (*AVGResponse) ProtoMessage()    {}
func (*AVGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edfed136edde2186, []int{1}
}

func (m *AVGResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AVGResponse.Unmarshal(m, b)
}
func (m *AVGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AVGResponse.Marshal(b, m, deterministic)
}
func (m *AVGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AVGResponse.Merge(m, src)
}
func (m *AVGResponse) XXX_Size() int {
	return xxx_messageInfo_AVGResponse.Size(m)
}
func (m *AVGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AVGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AVGResponse proto.InternalMessageInfo

func (m *AVGResponse) GetAverage() float32 {
	if m != nil {
		return m.Average
	}
	return 0
}

func init() {
	proto.RegisterType((*AVGRequest)(nil), "calpb.AVGRequest")
	proto.RegisterType((*AVGResponse)(nil), "calpb.AVGResponse")
}

func init() { proto.RegisterFile("calculator/calpb/calc.proto", fileDescriptor_edfed136edde2186) }

var fileDescriptor_edfed136edde2186 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x4f, 0x4e, 0xcc, 0x29, 0x48, 0x02, 0x91, 0xc9, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x11, 0x25, 0x15, 0x2e, 0x2e, 0xc7, 0x30, 0xf7,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xbc, 0xd2, 0xdc, 0xa4, 0xd4,
	0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x49, 0x9d, 0x8b, 0x1b, 0xac, 0xaa,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x82, 0x8b, 0x3d, 0xb1, 0x2c, 0xb5, 0x28, 0x31, 0x3d,
	0x15, 0xac, 0x8e, 0x29, 0x08, 0xc6, 0x35, 0xb2, 0x87, 0xcb, 0x08, 0x99, 0x70, 0xb1, 0x3b, 0x42,
	0x99, 0x82, 0x7a, 0x60, 0xcb, 0xf4, 0x10, 0x36, 0x49, 0x09, 0x21, 0x0b, 0x41, 0x8c, 0x55, 0x62,
	0xd0, 0x60, 0x74, 0x62, 0x8f, 0x82, 0x38, 0x2c, 0x89, 0x0d, 0xec, 0x4c, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x0f, 0x91, 0x6f, 0x30, 0xc5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AverageClient is the client API for Average service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AverageClient interface {
	Average(ctx context.Context, opts ...grpc.CallOption) (Average_AverageClient, error)
}

type averageClient struct {
	cc *grpc.ClientConn
}

func NewAverageClient(cc *grpc.ClientConn) AverageClient {
	return &averageClient{cc}
}

func (c *averageClient) Average(ctx context.Context, opts ...grpc.CallOption) (Average_AverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Average_serviceDesc.Streams[0], "/calpb.average/Average", opts...)
	if err != nil {
		return nil, err
	}
	x := &averageAverageClient{stream}
	return x, nil
}

type Average_AverageClient interface {
	Send(*AVGRequest) error
	CloseAndRecv() (*AVGResponse, error)
	grpc.ClientStream
}

type averageAverageClient struct {
	grpc.ClientStream
}

func (x *averageAverageClient) Send(m *AVGRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *averageAverageClient) CloseAndRecv() (*AVGResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AVGResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AverageServer is the server API for Average service.
type AverageServer interface {
	Average(Average_AverageServer) error
}

// UnimplementedAverageServer can be embedded to have forward compatible implementations.
type UnimplementedAverageServer struct {
}

func (*UnimplementedAverageServer) Average(srv Average_AverageServer) error {
	return status.Errorf(codes.Unimplemented, "method Average not implemented")
}

func RegisterAverageServer(s *grpc.Server, srv AverageServer) {
	s.RegisterService(&_Average_serviceDesc, srv)
}

func _Average_Average_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AverageServer).Average(&averageAverageServer{stream})
}

type Average_AverageServer interface {
	SendAndClose(*AVGResponse) error
	Recv() (*AVGRequest, error)
	grpc.ServerStream
}

type averageAverageServer struct {
	grpc.ServerStream
}

func (x *averageAverageServer) SendAndClose(m *AVGResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *averageAverageServer) Recv() (*AVGRequest, error) {
	m := new(AVGRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Average_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calpb.average",
	HandlerType: (*AverageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Average",
			Handler:       _Average_Average_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calpb/calc.proto",
}
