// Code generated by protoc-gen-go. DO NOT EDIT.
// source: libpb/libpb.proto

package bookpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateBookRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=Book,proto3" json:"Book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{1}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type CreateBookResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookResponse) Reset()         { *m = CreateBookResponse{} }
func (m *CreateBookResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookResponse) ProtoMessage()    {}
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{2}
}

func (m *CreateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookResponse.Unmarshal(m, b)
}
func (m *CreateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookResponse.Merge(m, src)
}
func (m *CreateBookResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookResponse.Size(m)
}
func (m *CreateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookResponse proto.InternalMessageInfo

func (m *CreateBookResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadBookRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBookRequest) Reset()         { *m = ReadBookRequest{} }
func (m *ReadBookRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBookRequest) ProtoMessage()    {}
func (*ReadBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{3}
}

func (m *ReadBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBookRequest.Unmarshal(m, b)
}
func (m *ReadBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBookRequest.Marshal(b, m, deterministic)
}
func (m *ReadBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBookRequest.Merge(m, src)
}
func (m *ReadBookRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBookRequest.Size(m)
}
func (m *ReadBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBookRequest proto.InternalMessageInfo

func (m *ReadBookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadBookResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBookResponse) Reset()         { *m = ReadBookResponse{} }
func (m *ReadBookResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBookResponse) ProtoMessage()    {}
func (*ReadBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{4}
}

func (m *ReadBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBookResponse.Unmarshal(m, b)
}
func (m *ReadBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBookResponse.Marshal(b, m, deterministic)
}
func (m *ReadBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBookResponse.Merge(m, src)
}
func (m *ReadBookResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBookResponse.Size(m)
}
func (m *ReadBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBookResponse proto.InternalMessageInfo

func (m *ReadBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{5}
}

func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(m, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookResponse) Reset()         { *m = UpdateBookResponse{} }
func (m *UpdateBookResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBookResponse) ProtoMessage()    {}
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{6}
}

func (m *UpdateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookResponse.Unmarshal(m, b)
}
func (m *UpdateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookResponse.Merge(m, src)
}
func (m *UpdateBookResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBookResponse.Size(m)
}
func (m *UpdateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookResponse proto.InternalMessageInfo

func (m *UpdateBookResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBookRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{7}
}

func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(m, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBookResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookResponse) Reset()         { *m = DeleteBookResponse{} }
func (m *DeleteBookResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookResponse) ProtoMessage()    {}
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{8}
}

func (m *DeleteBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookResponse.Unmarshal(m, b)
}
func (m *DeleteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookResponse.Merge(m, src)
}
func (m *DeleteBookResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookResponse.Size(m)
}
func (m *DeleteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookResponse proto.InternalMessageInfo

func (m *DeleteBookResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ListBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{9}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

type ListBooksResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_725161990bee098b, []int{10}
}

func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (m *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(m, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "bookpb.Book")
	proto.RegisterType((*CreateBookRequest)(nil), "bookpb.CreateBookRequest")
	proto.RegisterType((*CreateBookResponse)(nil), "bookpb.CreateBookResponse")
	proto.RegisterType((*ReadBookRequest)(nil), "bookpb.ReadBookRequest")
	proto.RegisterType((*ReadBookResponse)(nil), "bookpb.ReadBookResponse")
	proto.RegisterType((*UpdateBookRequest)(nil), "bookpb.UpdateBookRequest")
	proto.RegisterType((*UpdateBookResponse)(nil), "bookpb.UpdateBookResponse")
	proto.RegisterType((*DeleteBookRequest)(nil), "bookpb.DeleteBookRequest")
	proto.RegisterType((*DeleteBookResponse)(nil), "bookpb.DeleteBookResponse")
	proto.RegisterType((*ListBooksRequest)(nil), "bookpb.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "bookpb.ListBooksResponse")
}

func init() { proto.RegisterFile("libpb/libpb.proto", fileDescriptor_725161990bee098b) }

var fileDescriptor_725161990bee098b = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0x15, 0x1b, 0x18, 0x8d, 0xc2, 0xc4, 0x60, 0xe9, 0xa9, 0xae, 0x1c, 0x38, 0x18, 0x34,
	0xa8, 0x67, 0x23, 0xc2, 0x81, 0xc4, 0x53, 0xd5, 0x0b, 0x37, 0x6a, 0x37, 0xb1, 0x81, 0xb8, 0xb5,
	0xbb, 0x7c, 0xb3, 0xbf, 0x61, 0x76, 0xbb, 0x65, 0x6b, 0x17, 0xa2, 0x97, 0x26, 0x6f, 0xe6, 0xcd,
	0x9b, 0xd7, 0x79, 0x59, 0xe8, 0xae, 0xd3, 0x38, 0x8b, 0xaf, 0xd5, 0x77, 0x94, 0xe5, 0x4c, 0x30,
	0xf4, 0x62, 0xc6, 0x56, 0x59, 0x4c, 0x16, 0xd0, 0x9c, 0x30, 0xb6, 0xc2, 0x13, 0x70, 0xe7, 0x89,
	0xef, 0x84, 0xce, 0xb0, 0x1d, 0xb9, 0xf3, 0x04, 0xcf, 0xe0, 0xf0, 0x35, 0x15, 0x6b, 0xea, 0xbb,
	0xaa, 0x54, 0x00, 0xec, 0x81, 0xf7, 0xb8, 0x11, 0x1f, 0x2c, 0xf7, 0x0f, 0x54, 0x59, 0x23, 0xc9,
	0xce, 0xf2, 0xf4, 0x9d, 0xfa, 0xcd, 0xd0, 0x19, 0xba, 0x51, 0x01, 0xc8, 0x3d, 0x74, 0x9f, 0x72,
	0xba, 0x14, 0x54, 0x6e, 0x88, 0xe8, 0xd7, 0x86, 0x72, 0x81, 0x61, 0xb1, 0x50, 0xad, 0x3a, 0x1a,
	0x1f, 0x8f, 0x0a, 0x1f, 0x23, 0x45, 0x51, 0x1d, 0x32, 0x00, 0xac, 0x8e, 0xf1, 0x8c, 0x7d, 0x72,
	0x5a, 0x37, 0x48, 0x2e, 0xe0, 0x34, 0xa2, 0xcb, 0xa4, 0x2a, 0x5d, 0xa7, 0xdc, 0x41, 0xc7, 0x50,
	0xb4, 0x4c, 0x08, 0xcd, 0x78, 0xef, 0x7a, 0x09, 0xa4, 0xeb, 0xb7, 0x2c, 0xb1, 0x5d, 0xff, 0x31,
	0x36, 0x00, 0xac, 0x8e, 0xed, 0x71, 0x7d, 0x09, 0xdd, 0x29, 0x5d, 0xd3, 0xdf, 0xe2, 0x75, 0xd2,
	0x15, 0x60, 0x95, 0xa4, 0xa5, 0x7a, 0xe0, 0x71, 0xb1, 0x14, 0x1b, 0xae, 0x98, 0xad, 0x48, 0x23,
	0x82, 0xd0, 0x79, 0x4e, 0xb9, 0x90, 0x5c, 0xae, 0x15, 0xe5, 0x3f, 0x54, 0x6a, 0xff, 0xfd, 0xf5,
	0xf1, 0xb7, 0x0b, 0x6d, 0x09, 0x5f, 0x04, 0xcb, 0x29, 0xce, 0x00, 0x4c, 0x0e, 0xd8, 0x2f, 0xf9,
	0x56, 0xa4, 0x41, 0xb0, 0xab, 0x55, 0x2c, 0x25, 0x0d, 0x7c, 0x80, 0x56, 0x99, 0x02, 0x9e, 0x97,
	0xcc, 0x5a, 0x74, 0x81, 0x6f, 0x37, 0xb6, 0x02, 0x33, 0x00, 0x73, 0x59, 0xe3, 0xc3, 0x0a, 0xc9,
	0xf8, 0xb0, 0x83, 0x28, 0x64, 0xcc, 0x55, 0x8d, 0x8c, 0x15, 0x87, 0x91, 0xb1, 0x43, 0x20, 0x0d,
	0x9c, 0x42, 0x7b, 0x7b, 0x5a, 0xdc, 0xda, 0xae, 0x27, 0x10, 0xf4, 0x77, 0x74, 0x4a, 0x8d, 0x1b,
	0x67, 0xd2, 0x5a, 0xe8, 0x07, 0x18, 0x7b, 0xea, 0x3d, 0xde, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0xa3, 0x3e, 0x05, 0xa4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookStoreClient is the client API for BookStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookStoreClient interface {
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error)
	ReadBook(ctx context.Context, in *ReadBookRequest, opts ...grpc.CallOption) (*ReadBookResponse, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookResponse, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookResponse, error)
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (BookStore_ListBooksClient, error)
}

type bookStoreClient struct {
	cc *grpc.ClientConn
}

func NewBookStoreClient(cc *grpc.ClientConn) BookStoreClient {
	return &bookStoreClient{cc}
}

func (c *bookStoreClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error) {
	out := new(CreateBookResponse)
	err := c.cc.Invoke(ctx, "/bookpb.BookStore/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookStoreClient) ReadBook(ctx context.Context, in *ReadBookRequest, opts ...grpc.CallOption) (*ReadBookResponse, error) {
	out := new(ReadBookResponse)
	err := c.cc.Invoke(ctx, "/bookpb.BookStore/ReadBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookStoreClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookResponse, error) {
	out := new(UpdateBookResponse)
	err := c.cc.Invoke(ctx, "/bookpb.BookStore/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookStoreClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookResponse, error) {
	out := new(DeleteBookResponse)
	err := c.cc.Invoke(ctx, "/bookpb.BookStore/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookStoreClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (BookStore_ListBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BookStore_serviceDesc.Streams[0], "/bookpb.BookStore/ListBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookStoreListBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookStore_ListBooksClient interface {
	Recv() (*ListBooksResponse, error)
	grpc.ClientStream
}

type bookStoreListBooksClient struct {
	grpc.ClientStream
}

func (x *bookStoreListBooksClient) Recv() (*ListBooksResponse, error) {
	m := new(ListBooksResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookStoreServer is the server API for BookStore service.
type BookStoreServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	ReadBook(context.Context, *ReadBookRequest) (*ReadBookResponse, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*UpdateBookResponse, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*DeleteBookResponse, error)
	ListBooks(*ListBooksRequest, BookStore_ListBooksServer) error
}

// UnimplementedBookStoreServer can be embedded to have forward compatible implementations.
type UnimplementedBookStoreServer struct {
}

func (*UnimplementedBookStoreServer) CreateBook(ctx context.Context, req *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedBookStoreServer) ReadBook(ctx context.Context, req *ReadBookRequest) (*ReadBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBook not implemented")
}
func (*UnimplementedBookStoreServer) UpdateBook(ctx context.Context, req *UpdateBookRequest) (*UpdateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (*UnimplementedBookStoreServer) DeleteBook(ctx context.Context, req *DeleteBookRequest) (*DeleteBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (*UnimplementedBookStoreServer) ListBooks(req *ListBooksRequest, srv BookStore_ListBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}

func RegisterBookStoreServer(s *grpc.Server, srv BookStoreServer) {
	s.RegisterService(&_BookStore_serviceDesc, srv)
}

func _BookStore_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookStoreServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookpb.BookStore/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookStoreServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookStore_ReadBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookStoreServer).ReadBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookpb.BookStore/ReadBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookStoreServer).ReadBook(ctx, req.(*ReadBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookStore_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookStoreServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookpb.BookStore/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookStoreServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookStore_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookStoreServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookpb.BookStore/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookStoreServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookStore_ListBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBooksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookStoreServer).ListBooks(m, &bookStoreListBooksServer{stream})
}

type BookStore_ListBooksServer interface {
	Send(*ListBooksResponse) error
	grpc.ServerStream
}

type bookStoreListBooksServer struct {
	grpc.ServerStream
}

func (x *bookStoreListBooksServer) Send(m *ListBooksResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BookStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookpb.BookStore",
	HandlerType: (*BookStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookStore_CreateBook_Handler,
		},
		{
			MethodName: "ReadBook",
			Handler:    _BookStore_ReadBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookStore_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookStore_DeleteBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBooks",
			Handler:       _BookStore_ListBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "libpb/libpb.proto",
}
